{
 "title": "Sensors",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Bedroom temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensors_0_temperature/10000000000 - 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bedroom pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensors_0_pressure*0.00000000000750062",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bedroom humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensors_0_humidity/100000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cabinet temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensors_1_temperature/10000000000 - 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cabinet pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensors_1_pressure*0.00000000000750062",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cabinet humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensors_1_humidity/100000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "1661728",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bath_ch1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "1656268",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bath_ch0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bath battery",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bath_battery", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bedroom temperature",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensors_0_temperature/10000000000 - 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bedroom pressure",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "sensors_0_pressure*0.00000000000750062",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bedroom humidity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "sensors_0_humidity/100000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cabinet temperature",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensors_1_temperature/10000000000 - 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cabinet pressure",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "sensors_1_pressure*0.00000000000750062",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cabinet humidity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "sensors_1_humidity/100000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "1661729",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kitchen_ch1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "1661730",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kitchen_ch0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kitchen battery",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kitchen_battery", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "<iframe src=\"https://yandex.ru/map-widget/v1/?um=constructor%3A0d53bf8f6b4dae95f88edc81d91a302b4682b76f8b92bfa0574dc382c33cd944&amp;source=constructor\" width=\"100%\" height=\"250\" style=\"opacity:0.7;\" frameborder=\"0\"></iframe>"
   }
  }
 ]
}